import Head from "next/head";
import { ReactNode } from "react";
import SideMenu from "./SideMenu";

type PropType = {
  children: ReactNode;
};

export default function Layout({ children }: PropType): JSX.Element {
  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full items-center justify-between p-24">
        <SideMenu />
        {children}
      </main>
    </div>
  );
}
